trigger:
- master

pr:
- master

jobs:

- job: build_and_test
  displayName:  'Test using '
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      conda:
        gccVersion: '8'
        DEVITO_OPENMP: '0'
        MPI_INSTALL: '1'
        installWithPip: 'false'
        DEVITO_BACKEND: 'core'
        RUN_EXAMPLES: 'false'
        PYTHON_VERSION: '3.7'
      nompi-conda:
        gccVersion: '8'
        DEVITO_OPENMP: '1'
        MPI_INSTALL: '0'
        installWithPip: 'false'
        DEVITO_BACKEND: 'core'
        RUN_EXAMPLES: 'true'
        PYTHON_VERSION: '3.7'


  timeoutInMinutes: 120
  steps:
  - task: Docker@1
    displayName: "Build container"
    inputs:
      command: 'build'
      dockerFile: Dockerfile.pipelines
      arguments:
        --build-arg gccVersion=$(gccVersion)
        --build-arg installWithPip=$(installWithPip)
        --build-arg DEVITO_BACKEND=$(DEVITO_BACKEND)
        --build-arg DEVITO_OPENMP=$(DEVITO_OPENMP)
        --build-arg MPI_INSTALL=$(MPI_INSTALL)
        --build-arg RUN_EXAMPLES=$(RUN_EXAMPLES)
        --build-arg PYTHON_VERSION=$(PYTHON_VERSION)
  - task: Docker@1
    displayName: "Run tests"
    inputs:
      command: 'run'
      runInBackground: false
