name: Documentation

on: [release]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run documentation script
      run: |
        pip install doctr;
        doctr deploy . --built-docs docs/_build/html --key-path .deploy_key.enc;
