name: Documentation

on:
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Generate documentation
      run: |
        python -m pip install --upgrade pip 
        pip install sphinx sphinx_rtd_theme
        #html documentation generation
        cd docs && make html && cd ..;
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/_build/html
        
