name: Documentation

on:
  push:
    branches:    
      - master         # Push events on master branch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        python-version: 3.x 
    - name: Run documentation script
      run: |
        #html documentation generation
        pip install sphinx;
        cd docs && make html && cd ..;
        # html documentation generation through doctr
        pip install doctr;
        doctr deploy . --built-docs docs/_build/html --key-path .deploy_key.enc;
