name: CI-ops

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: pytest-ops
    runs-on: ubuntu-16.04

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Set up GCC 7
      run : |
        sudo apt-get install -y g++-7
        echo "::set-env name=CC::gcc-7"
        echo "::set-env name=CXX::g++-7"

    - name: Setup Devito environement
        echo "::set-env name=DEVITO_ARCH::gcc-7"
        echo "::set-env name=DEVITO_OPENMP::1"
        echo "::set-env name=DEVITO_MPI::0"
        echo "::set-env name=OMP_NUM_THREADS::2"
        echo "::set-env name=DEVITO_BACKEND::ops"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Test with pytest
      run: |
        pytest tests/