name: Jupyter Notebooks

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tutorials:
    name: Test Jupyter notebooks on ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      DEVITO_ARCH: "${{ matrix.compiler }}"
      DEVITO_OPENMP: ${{ matrix.openmp }}
      DEVITO_BACKEND: "core"
      PYTHON_VERSION: "3.7"

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false
      matrix:
        name: [
          ubuntu-16.04-gcc-py37,
          macOS-10.14-gcc-py37,
          macOS-10.14-clang-py37
          ]

        include:
          - name: ubuntu-16.04-gcc-py37
            os: ubuntu-16.04
            compiler: gcc-7
            openmp: 1

          - name: macOS-10.14-gcc-py37
            os: macos-latest
            compiler: gcc-9
            openmp: 1

          - name: macOS-10.14-clang-py37
            os: macos-latest
            compiler: clang
            openmp: 0

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install compilers for OSX
      if: runner.os == 'macOS'
      run: |
        if [ "${{ matrix.compiler }}" = "gcc-9" ]; then
          brew install gcc
        else
          sudo xcode-select -s /Applications/Xcode_11.app/Contents/Developer
        fi

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install matplotlib

    - name: Seismic notebooks
      run: |
        py.test --nbval examples/seismic/tutorials/

    - name: CFD notebooks
      run: |
        py.test --nbval examples/cfd

    - name: User api notebooks
      run: |
        py.test --nbval examples/userapi

    - name: User api notebooks
      run: |
        py.test --nbval examples/compiler
